parameters:
  DependsOn: ''
  ArtifactName: $(ArtifactName)

stages:
- stage: 'Release'
  dependsOn: ${{ parameters.DependsOn }}
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

  jobs:
  # track deployments on the environment
  - deployment: Deploy
    pool:
      vmImage: windows-latest
    # creates an environment if it doesn’t exist
    environment: net-standard-test-helper
    strategy:
      # default deployment strategy
      runOnce:
        deploy:
          steps:
          - task: NuGetCommand@2
            displayName: 'NuGet Publish'
            inputs:
              command: push
              feedsToUse: config
              externalFeedCredentials: NuGet
              packagesToPush: '$(System.DefaultWorkingDirectory)/$(ArtifactName)/*.nupkg'
              nuGetFeedType: external
              publishFeedCredentials: NuGet